// <auto-generated />
using System;
using ForumApp.Core.Context;
using ForumApp.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForumApp.Migrations
{
    [DbContext(typeof(ForumContext))]
    [Migration("20221225150618_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ForumApp.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CommentPostID")
                        .HasColumnType("int");

                    b.Property<int?>("CommentUserID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CommentPostID");

                    b.HasIndex("CommentUserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ForumApp.Models.Community", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("ForumApp.Models.DislikeComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CommentUserID")
                        .HasColumnType("int");

                    b.Property<int?>("CommnetDislikeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CommentUserID");

                    b.HasIndex("CommnetDislikeID");

                    b.ToTable("DislikeComments");
                });

            modelBuilder.Entity("ForumApp.Models.DislikePost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DislikePostPostID")
                        .HasColumnType("int");

                    b.Property<int?>("DislikePostUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DislikePostPostID");

                    b.HasIndex("DislikePostUserID");

                    b.ToTable("DislikePosts");
                });

            modelBuilder.Entity("ForumApp.Models.LikeComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CommentUserID")
                        .HasColumnType("int");

                    b.Property<int?>("CommnetLikeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CommentUserID");

                    b.HasIndex("CommnetLikeID");

                    b.ToTable("LikeComments");
                });

            modelBuilder.Entity("ForumApp.Models.LikePost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("LikePostPostID")
                        .HasColumnType("int");

                    b.Property<int?>("LikePostUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LikePostPostID");

                    b.HasIndex("LikePostUserID");

                    b.ToTable("LikePosts");
                });

            modelBuilder.Entity("ForumApp.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopicID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TopicID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ForumApp.Models.Topic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("ForumApp.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForumApp.Models.Comment", b =>
                {
                    b.HasOne("ForumApp.Models.Post", "CommentPost")
                        .WithMany()
                        .HasForeignKey("CommentPostID");

                    b.HasOne("ForumApp.Models.User", "CommentUser")
                        .WithMany()
                        .HasForeignKey("CommentUserID");

                    b.Navigation("CommentPost");

                    b.Navigation("CommentUser");
                });

            modelBuilder.Entity("ForumApp.Models.Community", b =>
                {
                    b.HasOne("ForumApp.Models.User", null)
                        .WithMany("Communities")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("ForumApp.Models.DislikeComment", b =>
                {
                    b.HasOne("ForumApp.Models.User", "CommentUser")
                        .WithMany()
                        .HasForeignKey("CommentUserID");

                    b.HasOne("ForumApp.Models.Comment", "CommnetDislike")
                        .WithMany("DislikeComments")
                        .HasForeignKey("CommnetDislikeID");

                    b.Navigation("CommentUser");

                    b.Navigation("CommnetDislike");
                });

            modelBuilder.Entity("ForumApp.Models.DislikePost", b =>
                {
                    b.HasOne("ForumApp.Models.Post", "DislikePostPost")
                        .WithMany()
                        .HasForeignKey("DislikePostPostID");

                    b.HasOne("ForumApp.Models.User", "DislikePostUser")
                        .WithMany()
                        .HasForeignKey("DislikePostUserID");

                    b.Navigation("DislikePostPost");

                    b.Navigation("DislikePostUser");
                });

            modelBuilder.Entity("ForumApp.Models.LikeComment", b =>
                {
                    b.HasOne("ForumApp.Models.User", "CommentUser")
                        .WithMany()
                        .HasForeignKey("CommentUserID");

                    b.HasOne("ForumApp.Models.Comment", "CommnetLike")
                        .WithMany("LikeComments")
                        .HasForeignKey("CommnetLikeID");

                    b.Navigation("CommentUser");

                    b.Navigation("CommnetLike");
                });

            modelBuilder.Entity("ForumApp.Models.LikePost", b =>
                {
                    b.HasOne("ForumApp.Models.Post", "LikePostPost")
                        .WithMany()
                        .HasForeignKey("LikePostPostID");

                    b.HasOne("ForumApp.Models.User", "LikePostUser")
                        .WithMany()
                        .HasForeignKey("LikePostUserID");

                    b.Navigation("LikePostPost");

                    b.Navigation("LikePostUser");
                });

            modelBuilder.Entity("ForumApp.Models.Post", b =>
                {
                    b.HasOne("ForumApp.Models.Topic", null)
                        .WithMany("Posts")
                        .HasForeignKey("TopicID");

                    b.HasOne("ForumApp.Models.User", null)
                        .WithMany("Posts")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("ForumApp.Models.Comment", b =>
                {
                    b.Navigation("DislikeComments");

                    b.Navigation("LikeComments");
                });

            modelBuilder.Entity("ForumApp.Models.Topic", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForumApp.Models.User", b =>
                {
                    b.Navigation("Communities");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
